name: Build & push image to GHCR
on: [push]                 # or 'release:', etc.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}   # owner/repo becomes image name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: { packages: write, contents: read }
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3       # enable Buildx
      - uses: docker/login-action@v3              # logs in using GITHUB_TOKEN
        with:
          registry: ${{ env.REGISTRY }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:5.3.0-sdxl
          build-args: RP_VERSION=5.3.0
